# Generated by Django 3.1.6 on 2021-02-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_ram', models.CharField(max_length=55)),
                ('Server_cpu', models.CharField(max_length=55)),
                ('Server_os', models.CharField(max_length=55)),
                ('Server_graphic', models.CharField(max_length=100)),
                ('Server_storage', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
